using UnityEngine;

public class SingletonMonoBehaviourAutoGenerated<T> : MonoBehaviour where T : MonoBehaviour
{
    static T _instance;

    public static T Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType<T>();

                if (_instance == null)
                {
                    GameObject singleton = new GameObject(typeof(T).Name);
                    _instance = singleton.AddComponent<T>();
                }
            }

            return _instance;
        }
    }

    public virtual void Awake()
    {
        if (_instance == null)
        {
            _instance = this as T;
            gameObject.transform.SetParent(null);
            DontDestroyOnLoad(gameObject);
        }
        else
        {
            Debug.LogWarning($"2 TANE SINGLETON {_instance.GetType().Name} KOPYASI VAR. BURAYI KONTROL EDIN");
            if (_instance != this as T)
            {
                Destroy(gameObject);
            }
            else
            {
                Debug.LogWarning(
                    $"SINGLETON {_instance.GetType().Name} ' KENDI AWAKE'INDEN ONCE ERISILIYOR. BURAYI KONTROL EDIN");
                DontDestroyOnLoad(gameObject);
            }
        }
    }
}